apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
    envFrom:
    - secretRef:
        name: db-secret
  volumes:
  - name: foo
    secret:
      secretName: mysecret
